### ISSUE TITLE
support for single sign-on with subversion?

### ISSUE THREAD

**Issue by mgrabner** [YvesR/mod_authn_ntlm#10]
Hi!

I tried to setup mod_auth_ntlm and subversion-1.9.0 with apache-2.4.16 to support single sign-on for subversion, but didn't succeed (more details are discussed here: https://www.apachehaus.com/forum/index.php?topic=1299.0).

The question I wanted to ask here is whether such a configuration (mod_auth_ntlm + subversion) is supposed to work, or if there are any known limitations and/or incompatibilities. I assumed it had at least been considered since SVNPathAuthz is explicitly mentioned as an example in the documentation of the NTLMChainAuth option.

Can you please clarify or (even better :-) give a configuration hint?

Thanks & kind regards,
Markus

**Comment by YvesR** [comment]
Hello,
I have no clue about SVN SSO but all what the NTLM module does is to validate a user or group and finally you can use the rewrite engine to pass data to the target application.

Here is a sample config that works for me. The application behind just get the remote user.

```
# if windows/ntlm auth used
  <Location /ror_auth >
    AuthName "Informer"
    AuthType SSPI
    NTLMAuth On
    NTLMAuthoritative On
    # domain need to be set to your domain
    # NTLMDefaultDomain domain.local
    #require valid-user
    <RequireAll>
        <RequireAny>
            Require valid-user
        </RequireAny>
        <RequireNone>
            Require user "ANONYMOUS LOGON"
            Require user "NT-AUTORITÄT\ANONYMOUS-ANMELDUNG"
        </RequireNone>
    </RequireAll>
    # use this to add the authenticated username to you header
    # so any backend system can fetch the current user
    # rewrite_module needs to be loaded then
    RewriteEngine On
    RewriteCond %{LA-U:REMOTE_USER} (.+)
    RewriteRule . - [E=RU:%1,NS]
    RequestHeader set X_ISRW_PROXY_AUTH_USER %{RU}e
  </Location>
```

**Comment by JBlond** [comment]
The issue on topic=1299.0 on Apachehaus forum wasn't that NTLM isn't working. mgrabner tried to use SSPI provider combined with mod_authz_svn. 

For me it worked using the AD SID's 

```
[/]
S-1-1-0=r
S-1-5-21-368584716-2338757681-3636766667-1003=rw
```


S-1-1-0 = Everyone ( "Jeder" in the German version )

**Comment by JBlond** [comment]
I found in the source code
- `NTLMChainAuth` => set to 'on' if you want an alternative authorization module like SVNPathAuthz to work at the same level
