### ISSUE TITLE
 NTLMDefaultDomain - Not Working

### ISSUE THREAD

**Issue by laurin1** [YvesR/mod_authn_ntlm#15]
Testing this from an iPad, this does not work. I have to enter the username as domain\username, even with NTLMDomain "domain" configured.

The failure is producing this in the log:

[Tue Jul 19 11:58:40.327870 2016] [auth_ntlm:error] [pid 15304:tid 1228](OS 1326)The user name or password is incorrect.  : [client 192.168.1.7:61797] authentication failure for "/": user unknown

From the code, that means that neither hdr->User or hdr->Domain are set. Why would hdr->User not be set?

**Comment by laurin1** [comment]
I must be losing my mind, because I'm using NTLMDomain. I just tried using NTLMDefaultDomain and I get this:

AH00526: Syntax error on line 39 of C:/apache/conf/vhosts/httpd-vhosts-intranet_local.conf:
Invalid command 'NTLMDefaultDomain', perhaps misspelled or defined by a module not included in the server configuration

**Comment by laurin1** [comment]
I just searched the code and I can't find NTLMDefaultDomain, only NTLMDomain.

**Comment by YvesR** [comment]
There is no default domain implementation in this module.
Did you try `user@domain`? I tried this and works for me.

**Comment by laurin1** [comment]
Yes, user@domain and domain\user works, but it's a pain for users to have to type their username (which is their full name) and the domain, especially on an iPad. We don't have to do this right on IIS and as we move towards switching to Apache, this is something I would like to fix.

**Comment by YvesR** [comment]
@laurin1 for you info,
we plan to implement `NTLMDefaultDomain`, hope next couple of weeks.

**Comment by laurin1** [comment]
Awesome. I looked at the code in an attempt to provide a PR, but I have not been able to spend the time to figure out it yet.

**Comment by YvesR** [comment]
Hello @laurin1 
NTLMDefaultDomain is implemented now. BUT:
Modern browsers send NTLM v2 headers which are not possible to modify.
In result this means the property only works with BASIC Auth. So in your case you would need to setup a configuration with Basic Auth and SSL connection. Using NTLM still need to qualify the domain.

**Comment by laurin1** [comment]
@YvesR 

> Modern browsers send NTLM v2 headers which are not possible to modify.
I'm not sure what you mean - we use IIS & Windows Authentication with Internet Explorer 11, Edge, and Chrome and all 3 work just fine. How is this different?

**Comment by YvesR** [comment]
To add a default domain to a username we need to add the domain extracting header data and then add it to the username before authenticate against the domain-controller.

Coming with NTLM v2 we can not modify the username (anymore), the hash will not fit anymore so the authentication fails. That is the reason it is not possible to add default domain to NTLM v2 authentication. 

So as result we added the NTLMDefaultDomain property but it will work only with Basic Auth as we describe in the readme.md.
