### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by h0nIg** [YvesR/mod_authn_ntlm#17]
- please add notice to https://support.microsoft.com/en-us/kb/896861 for local ntlm authentication
- replace REMOTE_USER rewrites (conf/httpd.conf, INSTALL.txt) and instead use the following to prevent trouble with apache phases. will make trouble e.g. on local ntlm
  `RequestHeader set X-Remote-User expr=%{REMOTE_USER}`

**Comment by YvesR** [comment]
The issue that IE is not able to perform correct NTLM authentication is old. Current version IE 11 still behave like this? I thought only older IE does that.

**Comment by h0nIg** [comment]
The first issue is browser independent, since the windows stuff (sspi / lsasrv i think) will complain about the local domain. Therefore it is happening on iis too

**Comment by YvesR** [comment]
Hello @h0nIg,
i apologize for not be active on this thread. I did a test and you absolutely right.
The link to MS and the workaround method 1 works perfect for the scenario to log on local machine if you set a FQDN. I will update the readme file.

**Comment by YvesR** [comment]
@h0nIg About the second configuration please clarify what you think it should be changed.

**Comment by h0nIg** [comment]
@YvesR as far as i can remember there is a phase problem with the rewrite rule, because this is how rewrite works. remove the following and add the RequestHeader statement above:

```
    RewriteEngine On
    RewriteCond %{LA-U:REMOTE_USER} (.+)
    RewriteRule . - [E=RU:%1]
    RequestHeader set X_ISRW_PROXY_AUTH_USER %{RU}e
```

**Comment by YvesR** [comment]
Ok so you say remove Rewrite, so I tried and my setup works with this:

`RequestHeader set X_ISRW_PROXY_AUTH_USER expr=%{REMOTE_USER}`

But I will dig deeper into it to find out the cause why it should be better.

**Comment by YvesR** [comment]
Updated documentation.
