### ISSUE TITLE
Makefile errors

### ISSUE THREAD

**Issue by gitrobert42** [YvesR/mod_authn_ntlm#20]
running make generates a number of errors like 

> Makefile:45: *** missing separator.  Stop.

**Comment by YvesR** [comment]
Hello,
try revert to the source before January, 12 and try again.
A developer commit code on my account (tho I still don't know how it was signed under my account as I made him a collaborator). The code seems to be corrupt on some place.
If this works I will rollback the changes and need to find a resource to dig into it.

**Comment by JBlond** [comment]
I try to take a look into at the week end. 
@gitrobert42 Which VS Version do you use?

**Comment by JBlond** [comment]
I used the following paths ( changed the x86 to x64 for the 64 bit in the apachedir)

```
APACHEDIR=C:\build\httpd-2.4.20-x86-vc14
MSVCDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
PLATSDKDIR=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A
EXTRAARCH=.
```

The Build x86 build went fine from my last commit https://github.com/JBlond/mod_authn_ntlm/commit/5e0b604f6e3643786dd0f3f9bb3610817a9fe738 (my repo)

The x64 Build however throws an error 
I changed line 54 from the make file to **DEFINES=/D WIN64**

```
        cl /nologo /W3 /WX /LD /MT /Ot /Ox /Oi /Oy /Ob2 /GF /Gy  /I "C:\build\ht
tpd-2.4.20-x64-vc14\include" /I "C:\build\httpd-2.4.20-x64-vc14\srclib\apr\inclu
de" /I "C:\build\httpd-2.4.20-x64-vc14\srclib\apr-util\include" /I "C:\build\htt
pd-2.4.20-x64-vc14\os\win32" /I "C:\Program Files (x86)\Microsoft SDKs\Windows\v
10.0A\include" /I "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\includ
e" /D WIN64 /c %CD%\src\mod_ntlm_interface.c /FoRelease\mod_ntlm_interface.obj
mod_ntlm_interface.c
C:\build\mod_authn_ntlm\src\mod_ntlm_interface.c(250): error C2220: warning trea
ted as error - no 'object' file generated
C:\build\mod_authn_ntlm\src\mod_ntlm_interface.c(250): warning C4267: '=': conve
rsion from 'size_t' to 'unsigned long', possible loss of data
C:\build\mod_authn_ntlm\src\mod_ntlm_interface.c(264): warning C4267: '=': conve
rsion from 'size_t' to 'unsigned long', possible loss of data
NMAKE : fatal error U1077: 'cl' : return code '0x2'
Stop.
```

size_t, time_t, and ptrdiff_t are 64-bit values on 64-bit Windows operating systems.  While unsigned long is 32 bit.

See https://msdn.microsoft.com/en-us/library/3b2e7499.aspx

**Comment by YvesR** [comment]
Ok, so 32 bit version runs but compile 64 bit won't. The guy who worked on the latest code said it should work. So it seems someone has to take care of this...

**Comment by JBlond** [comment]
@diovoemor Could you take a look at it? Can we change the definition in https://github.com/YvesR/mod_authn_ntlm/blob/master/src/mod_ntlm.h#L118 and https://github.com/YvesR/mod_authn_ntlm/blob/master/src/mod_ntlm.h#L119 to get it working for x64 ? 
@YvesR it is a bit hard to track what happend within that commit on the 12th. Cause many changed are only line wrapping not real code changes.

**Comment by YvesR** [comment]
Yeah I apologize, 
I did set a freelancer for the project as contributor. Until today I do not know how he could commit sources on "my name" as I didn't push it.

His job was to add the `NTLMDefaultDomain` feature so we could skip the domain\username login e.g. on tablets like the iPad. Nevertheless he told me that this do not work with NTLM2 as I updated in the readme.md file. But I thought the changes were made that this at least works with basic-auth.

So the task is to review now if this source works as expected and can be compiled. I have no environment at the moment and to less time to do myself for now but I try find someone who will.

**Comment by JBlond** [comment]
I did as best as I could to compare the two revisiona and ignore the white space changes that commit made and the line wrappings that the IDE made.
Here it is https://gist.github.com/JBlond/5f39a8dc78854a9e80261d4cacbfb13d

Do I get the shirt now?!

**Comment by YvesR** [comment]
fixed that problem with a colleague and changed to CMake. check read-me how to build 32 and/or 64 bit build.
