### ISSUE TITLE
Could you please tag releases

### ISSUE THREAD

**Issue by diovoemor** [YvesR/mod_authn_ntlm#21]
I wish you would tag releases after fixing bugs or whatever. I have a nice little gizmo that monitors releases, not single commits after 10 months. At which point come 4 months later I get a user coming to me asking for a new release of the module. I'd have known back in 01/2017 if you had made a release and I had not  had to wait till one of my users asked.

I do not use this module myself but it would surely help me out (Apache Haus).
Call what's here now 1.0.8 (since 1.0.7 was back in march 2016 and I released it as such), update the .rc and tag.

Thanks in advance.

**Comment by JBlond** [comment]
@YvesR  it would be nice to have a new release

**Comment by YvesR** [comment]
I will, but need to check current code first.
As I already mentioned some other developer updated source and it needs to be checked if the master works as expected. Due very little time help is welcome.

**Comment by JBlond** [comment]
issue #20 shows that at least x86 builds, but not x64. I think that should be fixed before releasing a version.

**Comment by YvesR** [comment]
Updated current status and tagged.
