### ISSUE TITLE
No access to $_SERVER['REMOTE_USER']

### ISSUE THREAD

**Issue by haakym** [YvesR/mod_authn_ntlm#26]
I am using the Laragon WAMP server from https://laragon.org/ which uses Apache/2.4.27 (Win64).

**Firstly**, downloading the zip from the github repo here (both branches i.e. `master` and `stable-1.0-32/64bit` and the tagged version v1.0) caused the following error when running Apache:

![image](https://user-images.githubusercontent.com/832687/31229391-70ccc000-a9d8-11e7-80c6-f7417d4f302d.png)

Please note that I followed the instructions in the readme for each case and it resulted in the same error message.

So I ended up downloading the software from here: https://www.apachehaus.com/cgi-bin/download.plx and no longer experienced the error when running Apache.

**Secondly**, after getting the module to run successfully I can now see it displayed on a page displaying `php_info()`, however, I have no access to `$_SERVER['REMOTE_USER']`.

I am using the following configuration in my virtual host:

```
<VirtualHost *:8000> 
  DocumentRoot "E:/laragon/www/authtest/"
  ServerName authtest.dev
  ServerAlias *.authtest.dev

  <Location /authenticate >
    #AllowOverride None
    AuthName "Private location"
    AuthType SSPI
    NTLMAuth On
    NTLMAuthoritative On
    <RequireAll>
      <RequireAny>
        Require valid-user
        #require sspi-user EMEA\group_name
      </RequireAny>
      <RequireNone>
        Require user "ANONYMOUS LOGON"
        Require user "NT-AUTORITÄT\ANONYMOUS-ANMELDUNG"
      </RequireNone>
    </RequireAll>
    # use this to add the authenticated username to you header
    # so any backend system can fetch the current user
    # rewrite_module needs to be loaded then
    # while X_ISRW_PROXY_AUTH_USER is your header name
    RequestHeader set X_ISRW_PROXY_AUTH_USER expr=%{REMOTE_USER}
  </Location>
</VirtualHost>
```

Can anyone advise what I should be doing differently to get access to `$_SERVER['REMOTE_USER']` from PHP.

Thank you and a huge thanks for maintaining this software!

**Comment by neongrau** [comment]
`RequestHeader set X_ISRW_PROXY_AUTH_USER expr=%{REMOTE_USER}`
Is the line where you define the Header that you want to make available to your application.
So either change the name to something else or try `$_SERVER['X_ISRW_PROXY_AUTH_USER']`

**Comment by haakym** [comment]
@neongrau thanks for your speedy reply!

I am var_dump-ing the server var currently, like this: `var_dump($_SERVER)` and do not currently have access to `$_SERVER['X_ISRW_PROXY_AUTH_USER']` any idea on how I may debug this?

And I assume I need to change the code to `RequestHeader set REMOTE_USER expr=%{REMOTE_USER}`?

**Comment by neongrau** [comment]
I think there was a reason to name the Header to something visibly custom instead of the common REMOTE_USER.

If you don't get it by the name `X_ISRW_PROXY_AUTH_USER` then renaming it to `REMOTE_USER`will most likely not help.

But yes try to debug by dumping all headers to see if you can find it.

**Comment by neongrau** [comment]
maybe try so simplify your config block into this:

```
RewriteEngine On
<Location /authenticate >
    #AllowOverride None
    AuthName "Private location"
    AuthType SSPI
    NTLMAuth On
    NTLMAuthoritative On
    require valid-user
    RequestHeader set X_ISRW_PROXY_AUTH_USER expr=%{REMOTE_USER}
</Location>
```
and ofc you have to access this in the browser with an URL that has the `/authenticate`
path like e.g. `http://authtest.dev:8000/authenticate/test.php`

**Comment by haakym** [comment]
@neongrau Thanks again for your replies.

Thanks for explaining that the `<Location>` value applies to the path, sorry to say my Apache knowledge is scarce! I've used the following config in my virtual host file `authtest.dev.conf`. I modified the location to `/` to apply to the whole folder.

```
<VirtualHost *:8000>
  DocumentRoot "E:/laragon/www/authtest/"
  ServerName authtest.dev
  ServerAlias *.authtest.dev
  
  RewriteEngine On
  <Location />
      #AllowOverride None
      AuthName "Private location"
      AuthType SSPI
      NTLMAuth On
      NTLMAuthoritative On
      require valid-user
      RequestHeader set X_ISRW_PROXY_AUTH_USER expr=%{REMOTE_USER}
  </Location>

</VirtualHost>
```

And I get the login prompt:

![image](https://user-images.githubusercontent.com/832687/31268934-5ccb82be-aa76-11e7-876f-655b498b0eb1.png)

So I guess that's a start?

Now I have another issue. Any login details I enter don't work. I've tried varying combinations including the use of the domain:

- username
- username\DOMAIN
- username@DOMAIN

... after checking the readme, I've just realised it's probably because of this: https://support.microsoft.com/en-us/help/896861/you-receive-error-401-1-when-you-browse-a-web-site-that-uses-integrate

I'll try the workaround or to access the server from a different PC.

Finally, I'd like to ask if there's a way to **switch off** the login prompt as I only really need access to the username. Or is the login required to get access to the username? I was previously using `mod_authnz_sspi` which in Chrome and IE didn't prompt for login details and would set the username in `$_SERVER['REMOTE_USER']`. I had this set up with the following config...

```
<Directory "c:/wamp/www/authtest">
  Options None
  AllowOverride All
  Order allow,deny
  Allow from all

  AuthName "SSPI Protected Place"
  AuthType SSPI
  SSPIAuth On
  SSPIAuthoritative On
  SSPIOfferBasic On
  SSPIOmitDomain Off
  Require valid-user
</Directory>
```

Thanks!

**Comment by neongrau** [comment]
When you get the login prompt you should be able to login with any credentials that would dallow you to log in on the machine that is running the Apache server. But yes, try from a different machine first.

Putting the authentication on the whole web is not a good idea as the auth process is a back and forth between client and server you would add at least 2 extra requests for every normal request which is quite bad for performance.
Normally you would have a login handling page there and after successful authentication you store that info in the server session.

If chrome and IE ask or a login you might want to check IE's settings about the zone at the bottom of the Security Settings there is a block "User Authentication" which defaults to "...only in Intranet zone". So you could either put your site to the Intranet zone or change the settings. (Chrome uses IE settings for that).

**Comment by haakym** [comment]
> Putting the authentication on the whole web is not a good idea as the auth process is a back and forth between client and server you would add at least 2 extra requests for every normal request which is quite bad for performance.
Normally you would have a login handling page there and after successful authentication you store that info in the server session.

Ah, okay. I thought that might be the case. Thank you for clarifying. 

> If chrome and IE ask or a login you might want to check IE's settings about the zone at the bottom of the Security Settings there is a block "User Authentication" which defaults to "...only in Intranet zone". So you could either put your site to the Intranet zone or change the settings. (Chrome uses IE settings for that).

Great. Looks like it's already set!

![image](https://user-images.githubusercontent.com/832687/31270387-1ea2e65c-aa7c-11e7-839b-f976c38fbe23.png)

Thank you for all your help so far @neongrau. I'm optimistic I should get this working pretty soon and can close this issue. Cheers!

**Comment by haakym** [comment]
@YvesR Sorry, I didn't get round to closing this. I have got it working now! Thanks for sharing this project with everyone!

**Comment by YvesR** [comment]
Your welcome.
