### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by acosonic** [YvesR/mod_authn_ntlm#29]
Can this be compiled on Ubuntu?

**Comment by YvesR** [comment]
Hello,

short answer: no.

long answer: No chance for this now as the module uses windows specific libs for authentication. We discussed that already if this would be possible in our team but this would end in a bigger implementation. Back end need to authenticate then e.g. against LDAP protocol, but there are already such modules available doing something similar.

**Comment by acosonic** [comment]
Hm, I tought your module was update of http://modntlm.sourceforge.net/

for 2.4 ...

It throws just 2 errors, I don't know to fix it on 16.04 ubuntu...

**Comment by JBlond** [comment]
@acosonic There is mod_auth_kerb for directly going such a service or 

https://httpd.apache.org/docs/2.4/mod/mod_ldap.html
and
https://httpd.apache.org/docs/2.4/mod/mod_authnz_ldap.html

**Comment by acosonic** [comment]
Huh, I'm not sure would it work with this plugin for Redmine:
[http://rmplus.pro/en/redmine/plugins/single_auth](
http://rmplus.pro/en/redmine/plugins/single_auth)

```
<Location /login>
      AuthType NTLM
      NTLMAuth on
      NTLMAuthoritative on
      NTLMDomain CORPORATION.COM
      NTLMServer corp-dc1.corporation.com
      NTLMBackup corp-dc2.corporation.com
      require valid-user
</Location>
```

**Comment by JBlond** [comment]
> I'm not sure would it work with this plugin
Not sure means you haven't tried...

You still have the option of an ugly perl module

https://www.linuxquestions.org/questions/linux-newbie-8/ntlm-on-new-apache-2-4-in-debian-8-4-a-4175577795/

**Comment by acosonic** [comment]
Ah I was trying that, even was fixing some codes in perl module, replacing host-ip with client-ip etc.... But it's just causing apache to drop dead...

I think I'll try your first suggestions, then if it fails, follow this [http://blog.techutils.space/2016/02/redmine-ad-sso-setup.html](http://blog.techutils.space/2016/02/redmine-ad-sso-setup.html)
