### ISSUE TITLE
Apache Login Prompt

### ISSUE THREAD

**Issue by eldar134** [YvesR/mod_authn_ntlm#3]
How can I disable Apache Login Prompt for non-authenticated users?

**Comment by JBlond** [comment]
@eldar134 if this solved your issue can you please close this issue. Casue Yves merged the IE re-auth code in https://github.com/YvesR/mod_authn_ntlm/commit/30b728871bb27622bd5bfc60c899e9b7fe832f37

 Or if it did not solve your problem, please add details.
