### ISSUE TITLE
not a valid Win32 application

### ISSUE THREAD

**Issue by glenncarr** [YvesR/mod_authn_ntlm#30]
I apologize if this is a dumb question -- I used the .so that was in the repo, and I'm getting this error on a Server 2016 box while trying to add SSPI authentication to a CollabNet Subversion installation:

```
The Apache service named  reported the following error:
>>> httpd.exe: Syntax error on line 10 of C:/csvn/data/conf/httpd.conf: Cannot load lib/modules/mod_authn_ntlm.so into server: The Apache service named is not a valid Win32 application.    
```

Do I need to rebuild the .so?

Thanks,
Glenn

**Comment by YvesR** [comment]
You need to build the file for your special apache version for sure, else your apache can not load the specified module. Depends on VC apache is comipled with, also if 32 or 64 bit.
We made a detailed and simple how-to to compile it.

Alternative, Apache Haus does a great job to recompile this stuff, take a look at https://www.apachehaus.com/.

**Comment by glenncarr** [comment]
Thanks so much.  Found what I needed on https://www.apachehaus.com/
