### ISSUE TITLE
Authentication will fail open the page on the server itself with different url

### ISSUE THREAD

**Issue by YvesR** [YvesR/mod_authn_ntlm#5]
@Community: I did not figure out what is wrong, so maybe someone knows why and can help.
## Example:
- Server has name "Webserver"
- httpd.conf contains server name "Webserver"
- the virtual host entry has a different url => e.g. mysite.mydomain.com
- the module is used to authenticate the page

If you call the page with mysite.mydomain.com from a client all is fine. IE / Chrome uses SSO and other machines like on MAC OS a user credentials window popup and after it accept correct credentials and log on.
## Now the issue:

If you open a browser on the server where Apache is running and call the URL mysite.mydomain.com the authentication fails.

---

Authorization Required
This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

---

If you open a browser on the server and use the server name like http://webserver/ the authentication works.

This is frustrating when you log on the server as Administrator and try to open the page itself.

**Comment by TWAC** [comment]
Have you tried enabling *LogLevel debug*, and comparing the error.log output?

**Comment by YvesR** [comment]
Root cause of this is described in #17 .
Correct configuration will make open FQDN local on the server possible.
