### ISSUE TITLE
what additional header information is available?

### ISSUE THREAD

**Issue by RayDeanTech** [YvesR/mod_authn_ntlm#53]
I was successfully able to get Apache to forward the REMOTE_USER to a reverse proxy on the same server. as mentioned in the instructions:  `RequestHeader set X_ISRW_PROXY_AUTH_USER expr=%{REMOTE_USER}`

Apache :443 --> Express :5001  (same web server)

I can see several things in the Request Header, like `x-forwarded-for`, `x-forwarded-server`, and `x_isrw_proxy_auth_user`

Is there any additional information that I can forward about the user to the backend?  For example, can I forward group membership information?

What other information about the user is available after authorization?

Are there any additional variables in addition to `expr=%{REMOTE_USER}`?

**Comment by neongrau** [comment]
Nothing else is available. What you see are just basic headers from apache or whatever your client sent.

This mod is solely for authentication. What you're asking for is rather authorization and you would have program your backend to talk to your directory service.

`X_ISRW_PROXY_AUTH_USER` is also just a random header name. You could name it whatever you like.
And also you have to make sure Apache will delete that header if it gets sent by a client.
