### ISSUE TITLE
How to have 2 types of authentication?

### ISSUE THREAD

**Issue by BigPino67** [YvesR/mod_authn_ntlm#54]
How can I configure NTLM + BASIC or NTLM + LDAP for the same location?

**Comment by YvesR** [comment]
This module does what it indicate: authenticate against NTLM, there is no support or fallback to BASIC. LDAP is a different module > https://httpd.apache.org/docs/2.4/mod/mod_authnz_ldap.html

**Comment by neongrau** [comment]
@BigPino67  This should be general apache configuration by defining the other type(s) and `satisfy any`.

**Comment by herlex** [comment]
Hello,

i also stumbled upon this problem. The answer neongrau provided is Apache2.2 compatible but not Apache2.4. I tried a lot but could not get it to work that i am using NTLM Module as Main-Auth module and fallback to mod_auth_basic (.htpasswd) when NTLM doesn't find a valid user-id.

As described in the documentation it should be possible by "passing the accesscontrol to a lower module" (which i think should then be mod_auth_basic? Or what is meant with lower module here?)

> NTLMAuthoritative => set to 'off' to allow access control to be passed along to lower modules if the UserID is not known to this module

Also why is the exact same text at NTLMOfferNTLM as well? Do i need both to pass it to a lower module? Or is Authoritative enough?

Any help appreciated!
Thanks in advance.
